let DATA=[],SECTIONS={},current='all';
const $=id=>document.getElementById(id), grid=$('grid'), q=$('q'), tabs=$('tabs'), count=$('count'), rank=$('rank'), rarity=$('rarity'), modal=$('modal'), details=$('details');
function norm(s){return (s||'').toString().toLowerCase()}
function img(src,cls='icon'){return src?`<img class="${cls}" src="${src}" loading="lazy" onerror="this.style.display='none'">`:''}
function card(x,i){return `<article class="card" onclick="openItem(${i})">${img(x.img)}<div class="name">${x.name||'Без названия'}</div><div class="sub">${SECTIONS[x.section]||x.section||''} ${x.rank||''}</div>${x.rarity?`<div class="sub">${x.rarity}</div>`:''}</article>`}
function filtered(){let s=norm(q.value).trim(), r=rank.value, rar=rarity.value;return DATA.map((x,i)=>[x,i]).filter(([x])=>(current==='all'||x.section===current)&&(!r||x.rank===r)&&(!rar||x.rarity===rar)&&(!s||norm([x.name,x.desc,x.rank,x.rarity,(x.metas||[]).join(' '),(x.stats||[]).join(' ')].join(' ')).includes(s)))}
function render(){let arr=filtered();count.textContent=`Найдено: ${arr.length} / ${DATA.length}`;grid.innerHTML=arr.map(([x,i])=>card(x,i)).join('')||'<p style="padding:16px">Ничего не найдено</p>'}
function openItem(i){let x=DATA[i];details.innerHTML=`<div class="detailHead">${img(x.img,'')}<div><div class="detailTitle">${x.name||''}</div><div class="sub">${SECTIONS[x.section]||x.section||''} ${x.rank||''}</div></div></div><div class="chips">${(x.metas||[]).map(m=>`<span class="chip">${m}</span>`).join('')}</div>${x.desc?`<p class="desc">${x.desc}</p>`:''}${(x.stats||[]).length?`<ul class="stats">${x.stats.map(s=>`<li>${s}</li>`).join('')}</ul>`:''}`;modal.hidden=false;document.body.style.overflow='hidden'}
$('close').onclick=()=>{modal.hidden=true;document.body.style.overflow=''};modal.onclick=e=>{if(e.target===modal)$('close').click()};
function setup(){let keys=['all',...Object.keys(SECTIONS)];tabs.innerHTML=keys.map(k=>`<button class="tab ${k==='all'?'active':''}" data-k="${k}">${k==='all'?'Все':SECTIONS[k]}</button>`).join('');tabs.onclick=e=>{if(e.target.dataset.k){current=e.target.dataset.k;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.k===current));render()}};[...new Set(DATA.map(x=>x.rank).filter(Boolean))].sort().forEach(v=>rank.add(new Option(v,v)));[...new Set(DATA.map(x=>x.rarity).filter(Boolean))].sort().forEach(v=>rarity.add(new Option(v,v)));q.oninput=render;rank.onchange=render;rarity.onchange=render;render()}
fetch('data.json').then(r=>r.json()).then(j=>{DATA=j.items;SECTIONS=j.sections;setup()}).catch(e=>count.textContent='Не удалось загрузить data.json');
