
let DATA=[], filtered=[], shown=0, current='Все', compare=[];
const sections=['Все','Предметы','Питомцы','Классы','Навыки','Монстры','Боссы','Рейды','Постройки','Подземелья'];
const $=id=>document.getElementById(id);
fetch('data.json').then(r=>r.json()).then(d=>{DATA=d; init();});
function init(){ $('total').textContent=DATA.length; $('tabs').innerHTML=sections.map(s=>`<button class="${s==='Все'?'active':''}" onclick="tab('${s}',this)">${s}</button>`).join(''); $('q').oninput=apply; $('rank').onchange=apply; $('rarity').onchange=apply; apply(); }
function tab(s,el){current=s; document.querySelectorAll('#tabs button').forEach(b=>b.classList.remove('active')); el.classList.add('active'); apply();}
function text(e){return [e.title,e.section,e.rank,e.rarity,...e.description,...e.meta,...e.tags,...e.stats,...e.groups.flatMap(g=>[g.title,...g.items.map(i=>i.name)])].join(' ').toLowerCase();}
function apply(){const q=$('q').value.trim().toLowerCase(), rank=$('rank').value, rar=$('rarity').value; filtered=DATA.filter(e=>(current==='Все'||e.section===current)&&(!q||text(e).includes(q))&&(!rank||e.rank===rank)&&(!rar||e.rarity.toLowerCase().includes(rar))); shown=0; $('cards').innerHTML=''; more();}
function more(){const part=filtered.slice(shown,shown+60); shown+=part.length; $('cards').insertAdjacentHTML('beforeend', part.map(card).join('')); $('found').textContent=`${Math.min(shown,filtered.length)} / ${filtered.length}`; $('more').style.display=shown<filtered.length?'block':'none'; updateCompare();}
function card(e){return `<div class="card" onclick="openCard('${e.id}')"><img class="icon" src="${e.image}" loading="lazy" onerror="this.style.display='none'"><div><div class="name">${esc(e.title)}</div><div class="meta">${e.section} ${e.rank||''}<br>${esc(e.rarity||'')}</div><div class="desc">${esc((e.description||[]).join(' '))}</div></div><input class="chk" type="checkbox" onclick="event.stopPropagation();toggleCompare('${e.id}',this)" ${compare.includes(e.id)?'checked':''}></div>`}
function openCard(id){const e=DATA.find(x=>x.id===id); if(!e)return; $('modalBody').innerHTML=`<div class="head"><img class="big" src="${e.image}" onerror="this.style.display='none'"><div><div class="meta">${e.section}</div><div class="h">${esc(e.title)}</div><div>${e.rank?`<span class="pill">${e.rank}</span>`:''}${e.rarity?`<span class="pill">${esc(e.rarity)}</span>`:''}</div></div></div>${sec('Описание',e.description)}${sec('Данные',e.meta)}${sec('Особенности',e.tags)}${sec('Характеристики',e.stats)}${e.groups.map(g=>`<div class="sec"><h3>${esc(g.title)}</h3>${g.items.map(i=>`<div class="drop"><img src="${i.img}" onerror="this.style.display='none'"><span>${esc(i.name)}</span></div>`).join('')}</div>`).join('')}`; $('modal').classList.add('show');}
function sec(t,arr){return arr&&arr.length?`<div class="sec"><h3>${t}</h3>${arr.map(x=>`<div class="pill">${esc(x)}</div>`).join('')}</div>`:''}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function toggleCompare(id,cb){ if(cb.checked){ if(compare.length>=4){cb.checked=false; alert('Можно сравнить до 4 карточек'); return;} compare.push(id);} else compare=compare.filter(x=>x!==id); updateCompare();}
function updateCompare(){ $('cmp').textContent=`Сравнить (${compare.length})`; }
function showCompare(){ const es=compare.map(id=>DATA.find(e=>e.id===id)).filter(Boolean); if(!es.length) return; $('modalBody').innerHTML=`<div class="h">Сравнение</div><table><tr><th>Поле</th>${es.map(e=>`<th>${esc(e.title)}</th>`).join('')}</tr>${['section','rank','rarity'].map(k=>`<tr><td>${k}</td>${es.map(e=>`<td>${esc(e[k]||'')}</td>`).join('')}</tr>`).join('')}<tr><td>Описание</td>${es.map(e=>`<td>${esc((e.description||[]).join(' '))}</td>`).join('')}</tr><tr><td>Характеристики</td>${es.map(e=>`<td>${esc((e.stats||[]).join('\n'))}</td>`).join('')}</tr></table>`; $('modal').classList.add('show');}
function clearCompare(){compare=[]; document.querySelectorAll('.chk').forEach(c=>c.checked=false); updateCompare();}
