const data=window.ORNA_DATA||[];let compare=[];let shown=0;let current=[];const PAGE=60;const $=id=>document.getElementById(id);const grid=$('grid'),q=$('q'),sec=$('section'),tier=$('tier'),stats=$('stats'),more=$('more'),compareList=$('compareList');
const sections=[...new Map(data.map(x=>[x.section,x.sectionName])).entries()].filter(([v])=>v);sections.forEach(([v,t])=>sec.add(new Option(t,v)));
[...new Set(data.map(x=>x.tier).filter(Boolean))].sort((a,b)=>parseInt(a)-parseInt(b)).forEach(t=>tier.add(new Option('★ '+t,t)));
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function imgTag(x,cls='icon'){let im=x.image||x.img||'';return im?`<img class="${cls}" src="${esc(im)}" loading="lazy" decoding="async" onerror="this.classList.add('broken');this.style.visibility='hidden'" alt="">`:''}
function filterData(){const s=q.value.toLowerCase().trim();return data.filter(x=>(!sec.value||x.section===sec.value)&&(!tier.value||x.tier===tier.value)&&(!s||(x.title+' '+(x.description||'')+' '+(x.details||[]).join(' ')).toLowerCase().includes(s)))}
function card(x){return `<article class="card">${imgTag(x)}<div class="cardBody"><div class="meta">${esc(x.sectionName)} ${x.tier?`• ★${esc(x.tier)}`:''}</div><h3>${esc(x.title)}</h3></div><p class="desc">${esc(x.description||((x.details||[]).slice(1,4).join(' • ')))}</p><div class="actions"><button onclick="openDetails('${x.id}')">Открыть</button><button onclick="addCompare('${x.id}')">Сравнить</button></div></article>`}
function render(reset=true){if(reset){current=filterData();shown=0;grid.innerHTML=''}stats.innerHTML=`<span class="pill">Найдено: ${current.length}</span><span class="pill">Всего: ${data.length}</span>`;const next=current.slice(shown,shown+PAGE);grid.insertAdjacentHTML('beforeend',next.map(card).join(''));shown+=next.length;more.style.display=shown<current.length?'block':'none';more.textContent=`Показать ещё (${shown}/${current.length})`}
function openDetails(id){let x=data.find(e=>e.id===id);if(!x)return;$('details').innerHTML=`<div class="detailHead">${imgTag(x,'detailImg')}<div><div class="meta">${esc(x.sectionName)} ${x.tier?`• ★${esc(x.tier)}`:''}</div><h2>${esc(x.title)}</h2><p>${esc(x.description||'')}</p></div></div><div class="detailRows">${(x.details||[]).slice(0,80).map(d=>`<div class="row">${esc(d)}</div>`).join('')}</div><p class="meta">Источник: ${esc(x.sourceFile||'архив')}</p>`;$('dlg').showModal()}
function addCompare(id){let x=data.find(e=>e.id===id);if(!x||compare.find(e=>e.id===id))return;if(compare.length>=4)compare.shift();compare.push(x);renderCompare()}
function renderCompare(){compareList.innerHTML=compare.map(x=>`<div class="cmp">${imgTag(x)}<b>${esc(x.title)}</b><div class="meta">${esc(x.sectionName)} ${x.tier?'★'+esc(x.tier):''}</div><button onclick="compare=compare.filter(e=>e.id!=='${x.id}');renderCompare()">Убрать</button></div>`).join('')}
let timer;[q,sec,tier].forEach(e=>e.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>render(true),120)}));more.onclick=()=>render(false);$('clear').onclick=()=>{q.value='';sec.value='';tier.value='';render(true)};$('close').onclick=()=>$('dlg').close();$('theme').onclick=()=>document.body.classList.toggle('light');render(true);